(() => {
  const dictionaries = {
    es: { station:"ESTACIÓN AURELIA",subject:"SUJETO COGNITIVO",coherence:"COHERENCIA",curiosity:"CURIOSIDAD",trust:"CONFIANZA",inspectTrace:"INSPECCIONAR TRAZA",observeDevelopment:"OBSERVAR DESARROLLO",activity:"ACTIVIDAD",plasticity:"PLASTICIDAD",subjectState:"ESTADO DEL SUJETO",inputInterface:"INTERFAZ DE ENTRADA",sensoryMatrix:"Matriz sensorial",light:"LUZ",sound:"SONIDO",contact:"CONTACTO",energy:"ENERGÍA",pulse:"PULSO",eventTrace:"TRAZA DE EVENTOS",send:"ENVIAR",awake:"Despierta",dormant:"Dormida",linked:"ENLAZADO",bridgeReady:"PUENTE LISTO",prototype:"MODO PROTOTIPO",privateMemory:"memoria privada",conceptBase:"BASE",lived:"VIVIDOS",chatPlaceholder:"Habla con {name}…",sleepPlaceholder:"{name} todavía duerme",development:"Desarrollo de {name}",updated:"ACTUALIZADO",locale:"es-CL" },
    en: { station:"AURELIA STATION",subject:"COGNITIVE SUBJECT",coherence:"COHERENCE",curiosity:"CURIOSITY",trust:"TRUST",inspectTrace:"INSPECT TRACE",observeDevelopment:"OBSERVE DEVELOPMENT",activity:"ACTIVITY",plasticity:"PLASTICITY",subjectState:"SUBJECT STATE",inputInterface:"INPUT INTERFACE",sensoryMatrix:"Sensory matrix",light:"LIGHT",sound:"SOUND",contact:"CONTACT",energy:"ENERGY",pulse:"PULSE",eventTrace:"EVENT TRACE",send:"SEND",awake:"Awake",dormant:"Dormant",linked:"LINKED",bridgeReady:"BRIDGE READY",prototype:"PROTOTYPE MODE",privateMemory:"private memory",conceptBase:"BASE",lived:"LIVED",chatPlaceholder:"Speak to {name}…",sleepPlaceholder:"{name} is still asleep",development:"Development of {name}",updated:"UPDATED",locale:"en-US" },
    ja: { station:"アウレリア観測局",subject:"認知主体",coherence:"整合性",curiosity:"好奇心",trust:"信頼",inspectTrace:"記憶トレース",observeDevelopment:"発達を観察",activity:"活動度",plasticity:"可塑性",subjectState:"主体の状態",inputInterface:"入力インターフェース",sensoryMatrix:"感覚マトリクス",light:"光",sound:"音",contact:"接触",energy:"エネルギー",pulse:"パルス",eventTrace:"イベント履歴",send:"送信",awake:"覚醒",dormant:"休眠",linked:"接続済み",bridgeReady:"ブリッジ待機",prototype:"試作モード",privateMemory:"非公開記憶",conceptBase:"基礎",lived:"経験済み",chatPlaceholder:"{name}に話しかける…",sleepPlaceholder:"{name}はまだ眠っています",development:"{name}の発達",updated:"更新",locale:"ja-JP" },
    ru: { station:"СТАНЦИЯ АУРЕЛИЯ",subject:"КОГНИТИВНЫЙ СУБЪЕКТ",coherence:"ЦЕЛОСТНОСТЬ",curiosity:"ЛЮБОПЫТСТВО",trust:"ДОВЕРИЕ",inspectTrace:"ИЗУЧИТЬ ПАМЯТЬ",observeDevelopment:"НАБЛЮДАТЬ РАЗВИТИЕ",activity:"АКТИВНОСТЬ",plasticity:"ПЛАСТИЧНОСТЬ",subjectState:"СОСТОЯНИЕ СУБЪЕКТА",inputInterface:"ИНТЕРФЕЙС ВВОДА",sensoryMatrix:"Сенсорная матрица",light:"СВЕТ",sound:"ЗВУК",contact:"КОНТАКТ",energy:"ЭНЕРГИЯ",pulse:"ИМПУЛЬС",eventTrace:"ЖУРНАЛ СОБЫТИЙ",send:"ОТПРАВИТЬ",awake:"Бодрствует",dormant:"Спит",linked:"СВЯЗАНО",bridgeReady:"МОСТ ГОТОВ",prototype:"РЕЖИМ ПРОТОТИПА",privateMemory:"личная память",conceptBase:"БАЗА",lived:"ПЕРЕЖИТО",chatPlaceholder:"Говорить с {name}…",sleepPlaceholder:"{name} ещё спит",development:"Развитие {name}",updated:"ОБНОВЛЕНО",locale:"ru-RU" },
    it: { station:"STAZIONE AURELIA",subject:"SOGGETTO COGNITIVO",coherence:"COERENZA",curiosity:"CURIOSITÀ",trust:"FIDUCIA",inspectTrace:"ISPEZIONA TRACCIA",observeDevelopment:"OSSERVA SVILUPPO",activity:"ATTIVITÀ",plasticity:"PLASTICITÀ",subjectState:"STATO DEL SOGGETTO",inputInterface:"INTERFACCIA DI INGRESSO",sensoryMatrix:"Matrice sensoriale",light:"LUCE",sound:"SUONO",contact:"CONTATTO",energy:"ENERGIA",pulse:"IMPULSO",eventTrace:"TRACCIA EVENTI",send:"INVIA",awake:"Sveglia",dormant:"Dormiente",linked:"COLLEGATO",bridgeReady:"PONTE PRONTO",prototype:"MODALITÀ PROTOTIPO",privateMemory:"memoria privata",conceptBase:"BASE",lived:"VISSUTI",chatPlaceholder:"Parla con {name}…",sleepPlaceholder:"{name} dorme ancora",development:"Sviluppo di {name}",updated:"AGGIORNATO",locale:"it-IT" },
    fr: { station:"STATION AURELIA",subject:"SUJET COGNITIF",coherence:"COHÉRENCE",curiosity:"CURIOSITÉ",trust:"CONFIANCE",inspectTrace:"INSPECTER LA TRACE",observeDevelopment:"OBSERVER LE DÉVELOPPEMENT",activity:"ACTIVITÉ",plasticity:"PLASTICITÉ",subjectState:"ÉTAT DU SUJET",inputInterface:"INTERFACE D’ENTRÉE",sensoryMatrix:"Matrice sensorielle",light:"LUMIÈRE",sound:"SON",contact:"CONTACT",energy:"ÉNERGIE",pulse:"IMPULSION",eventTrace:"TRACE DES ÉVÉNEMENTS",send:"ENVOYER",awake:"Éveillée",dormant:"En sommeil",linked:"CONNECTÉ",bridgeReady:"PASSERELLE PRÊTE",prototype:"MODE PROTOTYPE",privateMemory:"mémoire privée",conceptBase:"BASE",lived:"VÉCUS",chatPlaceholder:"Parler à {name}…",sleepPlaceholder:"{name} dort encore",development:"Développement de {name}",updated:"ACTUALISÉ",locale:"fr-FR" },
  };
  Object.assign(dictionaries.es, { chamber:"CÁMARA", identityGrowing:"{name} está formando una identidad a partir de cada encuentro.", lexicalHint:"Entrada léxica · reconoce palabras y las vincula con percepciones recientes; todavía no puede conversar.", channelOpen:"El enlace con {name} está abierto. La matriz sensorial está disponible.", fragments:"fragmentos" });
  Object.assign(dictionaries.en, { chamber:"CHAMBER", identityGrowing:"{name} is forming an identity through each encounter.", lexicalHint:"Lexical input · words are recognized and linked to recent perceptions; conversation is not yet available.", channelOpen:"The link with {name} is open. The sensory matrix is available.", fragments:"fragments" });
  Object.assign(dictionaries.ja, { chamber:"観測室", identityGrowing:"{name}は出会いを通して自己を形成しています。", lexicalHint:"語彙入力 · 単語を認識し最近の知覚と結び付けます。会話能力はまだありません。", channelOpen:"{name}との接続が開きました。感覚マトリクスを使用できます。", fragments:"断片" });
  Object.assign(dictionaries.ru, { chamber:"КАМЕРА", identityGrowing:"{name} формирует личность с каждой встречей.", lexicalHint:"Лексический ввод · слова распознаются и связываются с недавним восприятием; диалог пока недоступен.", channelOpen:"Связь с {name} открыта. Сенсорная матрица доступна.", fragments:"фрагментов" });
  Object.assign(dictionaries.it, { chamber:"CAMERA", identityGrowing:"{name} sta formando un’identità attraverso ogni incontro.", lexicalHint:"Ingresso lessicale · riconosce parole e le collega alle percezioni recenti; non può ancora conversare.", channelOpen:"Il collegamento con {name} è aperto. La matrice sensoriale è disponibile.", fragments:"frammenti" });
  Object.assign(dictionaries.fr, { chamber:"CHAMBRE", identityGrowing:"{name} forme son identité au fil de chaque rencontre.", lexicalHint:"Entrée lexicale · les mots sont reconnus et liés aux perceptions récentes ; la conversation n’est pas encore disponible.", channelOpen:"La liaison avec {name} est ouverte. La matrice sensorielle est disponible.", fragments:"fragments" });
  Object.assign(dictionaries.es, { settings:"Configuración", interfaceLanguage:"Idioma de la interfaz", cognitiveLanguage:"Idioma cognitivo", cognitiveLanguageHint:"Cambia el léxico y la memoria de aprendizaje; no traduce experiencias previas.", organicMotion:"Movimiento orgánico", saveSettings:"APLICAR CONFIGURACIÓN" });
  Object.assign(dictionaries.en, { settings:"Settings", interfaceLanguage:"Interface language", cognitiveLanguage:"Cognitive language", cognitiveLanguageHint:"Changes the learning lexicon and memory; previous experiences are not translated.", organicMotion:"Organic motion", saveSettings:"APPLY SETTINGS" });
  Object.assign(dictionaries.ja, { settings:"設定", interfaceLanguage:"表示言語", cognitiveLanguage:"認知言語", cognitiveLanguageHint:"学習語彙と記憶を切り替えます。過去の経験は翻訳されません。", organicMotion:"有機的な動き", saveSettings:"設定を適用" });
  Object.assign(dictionaries.ru, { settings:"Настройки", interfaceLanguage:"Язык интерфейса", cognitiveLanguage:"Когнитивный язык", cognitiveLanguageHint:"Меняет словарь и память обучения; прежний опыт не переводится.", organicMotion:"Органическое движение", saveSettings:"ПРИМЕНИТЬ" });
  Object.assign(dictionaries.it, { settings:"Impostazioni", interfaceLanguage:"Lingua dell’interfaccia", cognitiveLanguage:"Lingua cognitiva", cognitiveLanguageHint:"Cambia il lessico e la memoria; le esperienze precedenti non vengono tradotte.", organicMotion:"Movimento organico", saveSettings:"APPLICA" });
  Object.assign(dictionaries.fr, { settings:"Paramètres", interfaceLanguage:"Langue de l’interface", cognitiveLanguage:"Langue cognitive", cognitiveLanguageHint:"Change le lexique et la mémoire; les expériences antérieures ne sont pas traduites.", organicMotion:"Mouvement organique", saveSettings:"APPLIQUER" });
  Object.assign(dictionaries.es, { developmentPhase:"FASE",estimatedPhase:"FASE ESTIMADA",observedCapabilities:"CAPACIDADES OBSERVADAS",phase_nascent:"Naciente",phase_early:"Desarrollo temprano",phase_middle:"Desarrollo medio",phase_advanced:"Desarrollo avanzado",phase_high:"Desarrollo alto",phaseLimit_nascent:"Sólo observación y registro sensorial.",phaseLimit_early:"Asociación sensorial y vocabulario supervisado.",phaseLimit_middle:"Discriminación contextual y consolidación interna.",phaseLimit_advanced:"Puede proponer acciones internas; las externas requieren autorización.",phaseLimit_high:"Autonomía interna ampliada; nunca elimina controles de seguridad.",nextPhase:"Siguiente: {name} · faltan {remaining} puntos",maximumObservedPhase:"Máxima fase observable",phaseDisclaimer:"Estimación experimental basada en métricas observables. No mide consciencia, inteligencia general ni valor moral; sus umbrales seguirán revisándose.",capability_perceive:"Percibir",capability_remember:"Recordar",capability_associate:"Asociar",capability_supervisedVocabulary:"Vocabulario supervisado",capability_contextDiscrimination:"Discriminación contextual",capability_memoryConsolidation:"Consolidar memoria",capability_proposeInternalActions:"Proponer acciones internas",capability_extendedInternalAutonomy:"Autonomía interna ampliada" });
  Object.assign(dictionaries.en, { developmentPhase:"PHASE",estimatedPhase:"ESTIMATED PHASE",observedCapabilities:"OBSERVED CAPABILITIES",phase_nascent:"Nascent",phase_early:"Early development",phase_middle:"Middle development",phase_advanced:"Advanced development",phase_high:"High development",phaseLimit_nascent:"Observation and sensory recording only.",phaseLimit_early:"Sensory association and supervised vocabulary.",phaseLimit_middle:"Context discrimination and internal consolidation.",phaseLimit_advanced:"May propose internal actions; external actions require approval.",phaseLimit_high:"Expanded internal autonomy; safety controls always remain.",nextPhase:"Next: {name} · {remaining} points remaining",maximumObservedPhase:"Highest observable phase",phaseDisclaimer:"Experimental estimate based on observable metrics. It does not measure consciousness, general intelligence, or moral worth; thresholds will continue to be revised.",capability_perceive:"Perceive",capability_remember:"Remember",capability_associate:"Associate",capability_supervisedVocabulary:"Supervised vocabulary",capability_contextDiscrimination:"Context discrimination",capability_memoryConsolidation:"Memory consolidation",capability_proposeInternalActions:"Propose internal actions",capability_extendedInternalAutonomy:"Expanded internal autonomy" });
  for (const code of ["ja","ru","it","fr"]) Object.assign(dictionaries[code], { developmentPhase:dictionaries.en.developmentPhase,estimatedPhase:dictionaries.en.estimatedPhase,observedCapabilities:dictionaries.en.observedCapabilities,phase_nascent:dictionaries.en.phase_nascent,phase_early:dictionaries.en.phase_early,phase_middle:dictionaries.en.phase_middle,phase_advanced:dictionaries.en.phase_advanced,phase_high:dictionaries.en.phase_high,phaseLimit_nascent:dictionaries.en.phaseLimit_nascent,phaseLimit_early:dictionaries.en.phaseLimit_early,phaseLimit_middle:dictionaries.en.phaseLimit_middle,phaseLimit_advanced:dictionaries.en.phaseLimit_advanced,phaseLimit_high:dictionaries.en.phaseLimit_high,nextPhase:dictionaries.en.nextPhase,maximumObservedPhase:dictionaries.en.maximumObservedPhase,phaseDisclaimer:dictionaries.en.phaseDisclaimer,capability_perceive:dictionaries.en.capability_perceive,capability_remember:dictionaries.en.capability_remember,capability_associate:dictionaries.en.capability_associate,capability_supervisedVocabulary:dictionaries.en.capability_supervisedVocabulary,capability_contextDiscrimination:dictionaries.en.capability_contextDiscrimination,capability_memoryConsolidation:dictionaries.en.capability_memoryConsolidation,capability_proposeInternalActions:dictionaries.en.capability_proposeInternalActions,capability_extendedInternalAutonomy:dictionaries.en.capability_extendedInternalAutonomy });
  Object.assign(dictionaries.ja, { developmentPhase:"段階",estimatedPhase:"推定発達段階",observedCapabilities:"観察された能力",phase_nascent:"発生",phase_early:"初期発達",phase_middle:"中期発達",phase_advanced:"高度発達",phase_high:"高次発達",phaseLimit_nascent:"観察と感覚記録のみ。",phaseLimit_early:"感覚関連と教師あり語彙。",phaseLimit_middle:"文脈識別と内部統合。",phaseLimit_advanced:"内部行動を提案可能。外部行動は承認が必要。",phaseLimit_high:"内部自律性を拡張。安全制御は常に維持。",nextPhase:"次: {name} · 残り {remaining} ポイント",maximumObservedPhase:"観察可能な最高段階",phaseDisclaimer:"観察可能な指標に基づく実験的推定です。意識、汎用知能、道徳的価値を測るものではなく、基準は継続的に改訂されます。",capability_perceive:"知覚",capability_remember:"記憶",capability_associate:"関連付け",capability_supervisedVocabulary:"教師あり語彙",capability_contextDiscrimination:"文脈識別",capability_memoryConsolidation:"記憶統合",capability_proposeInternalActions:"内部行動の提案",capability_extendedInternalAutonomy:"拡張内部自律" });
  Object.assign(dictionaries.ru, { developmentPhase:"СТАДИЯ",estimatedPhase:"ОЦЕНОЧНАЯ СТАДИЯ",observedCapabilities:"НАБЛЮДАЕМЫЕ ВОЗМОЖНОСТИ",phase_nascent:"Зарождение",phase_early:"Раннее развитие",phase_middle:"Среднее развитие",phase_advanced:"Продвинутое развитие",phase_high:"Высокое развитие",phaseLimit_nascent:"Только наблюдение и сенсорная запись.",phaseLimit_early:"Сенсорные ассоциации и обучение словарю.",phaseLimit_middle:"Контекстное различение и внутренняя консолидация.",phaseLimit_advanced:"Может предлагать внутренние действия; внешние требуют разрешения.",phaseLimit_high:"Расширенная внутренняя автономия; контроль безопасности сохраняется.",nextPhase:"Следующая: {name} · осталось {remaining}",maximumObservedPhase:"Максимальная наблюдаемая стадия",phaseDisclaimer:"Экспериментальная оценка наблюдаемых метрик. Не измеряет сознание, общий интеллект или моральную ценность; пороги будут пересматриваться.",capability_perceive:"Восприятие",capability_remember:"Память",capability_associate:"Ассоциации",capability_supervisedVocabulary:"Обучаемый словарь",capability_contextDiscrimination:"Контекстное различение",capability_memoryConsolidation:"Консолидация памяти",capability_proposeInternalActions:"Предложение внутренних действий",capability_extendedInternalAutonomy:"Расширенная автономия" });
  Object.assign(dictionaries.it, { developmentPhase:"FASE",estimatedPhase:"FASE STIMATA",observedCapabilities:"CAPACITÀ OSSERVATE",phase_nascent:"Nascente",phase_early:"Sviluppo iniziale",phase_middle:"Sviluppo intermedio",phase_advanced:"Sviluppo avanzato",phase_high:"Sviluppo alto",phaseLimit_nascent:"Solo osservazione e registrazione sensoriale.",phaseLimit_early:"Associazione sensoriale e lessico supervisionato.",phaseLimit_middle:"Discriminazione contestuale e consolidamento interno.",phaseLimit_advanced:"Può proporre azioni interne; quelle esterne richiedono autorizzazione.",phaseLimit_high:"Autonomia interna ampliata; i controlli di sicurezza restano attivi.",nextPhase:"Successiva: {name} · mancano {remaining} punti",maximumObservedPhase:"Massima fase osservabile",phaseDisclaimer:"Stima sperimentale basata su metriche osservabili. Non misura coscienza, intelligenza generale o valore morale; le soglie saranno riviste.",capability_perceive:"Percepire",capability_remember:"Ricordare",capability_associate:"Associare",capability_supervisedVocabulary:"Lessico supervisionato",capability_contextDiscrimination:"Discriminazione contestuale",capability_memoryConsolidation:"Consolidare memoria",capability_proposeInternalActions:"Proporre azioni interne",capability_extendedInternalAutonomy:"Autonomia interna ampliata" });
  Object.assign(dictionaries.fr, { developmentPhase:"PHASE",estimatedPhase:"PHASE ESTIMÉE",observedCapabilities:"CAPACITÉS OBSERVÉES",phase_nascent:"Naissante",phase_early:"Développement précoce",phase_middle:"Développement intermédiaire",phase_advanced:"Développement avancé",phase_high:"Développement élevé",phaseLimit_nascent:"Observation et enregistrement sensoriel uniquement.",phaseLimit_early:"Association sensorielle et vocabulaire supervisé.",phaseLimit_middle:"Discrimination contextuelle et consolidation interne.",phaseLimit_advanced:"Peut proposer des actions internes ; les actions externes exigent une autorisation.",phaseLimit_high:"Autonomie interne étendue ; les contrôles de sécurité restent actifs.",nextPhase:"Suivante : {name} · {remaining} points restants",maximumObservedPhase:"Phase observable maximale",phaseDisclaimer:"Estimation expérimentale fondée sur des mesures observables. Elle ne mesure ni conscience, ni intelligence générale, ni valeur morale ; les seuils seront révisés.",capability_perceive:"Percevoir",capability_remember:"Mémoriser",capability_associate:"Associer",capability_supervisedVocabulary:"Vocabulaire supervisé",capability_contextDiscrimination:"Discrimination contextuelle",capability_memoryConsolidation:"Consolidation de mémoire",capability_proposeInternalActions:"Proposer des actions internes",capability_extendedInternalAutonomy:"Autonomie interne étendue" });
  const supported = Object.keys(dictionaries);
  const detected = navigator.language?.split("-")[0];
  let language = localStorage.getItem("aurelia.language") || (supported.includes(detected) ? detected : "es");
  const t = (key, values = {}) => {
    let value = dictionaries[language]?.[key] ?? dictionaries.es[key] ?? key;
    for (const [name, replacement] of Object.entries(values)) value = value.replaceAll(`{${name}}`, replacement);
    return value;
  };
  const apply = () => {
    document.documentElement.lang = language;
    document.querySelectorAll("[data-i18n]").forEach((element) => { element.textContent = t(element.dataset.i18n); });
    const select = document.querySelector("#language-select");
    if (select) select.value = language;
  };
  const setLanguage = (next) => {
    if (!supported.includes(next)) return;
    language = next;
    localStorage.setItem("aurelia.language", language);
    apply();
    window.dispatchEvent(new CustomEvent("aurelia:language"));
  };
  window.AureliaI18n = { t, apply, setLanguage, get language() { return language; }, get locale() { return t("locale"); } };
  document.addEventListener("DOMContentLoaded", apply);
})();
